[workspace]
members = [
    "jexl-3000",
    "jexl-eval",
    "jexl-node",
    "jexl-parser",
    "jexl-python",
    "jexl-wasm",
    "parser-gen",
]
exclude = [
    "jexl-serverless",
]

[workspace.dependencies]
serde = "1.0"
serde_json = "1.0"
tikv-jemallocator = "0.5"