[package]
name = "jexl-3000"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
language-service = ["jexl-eval/language-service", "serde/derive", "dep:jexl-parser"]

[dependencies]
diacritics = "0.2.2"
jexl-eval = { path = "../jexl-eval" }
jexl-parser = { path = "../jexl-parser", optional = true }
ordered-float = "5.1"
serde_json.workspace = true
serde = { workspace = true, optional = true }
[target.'cfg(not(target_arch = "wasm32"))'.dependencies.time]
workspace = true
features = ["local-offset", "parsing", "formatting"]

[target.'cfg(target_arch = "wasm32")'.dependencies.time]
workspace = true
features = ["parsing", "formatting"]

[dev-dependencies]
rstest = "0.26.0"
tikv-jemallocator.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = "0.3"
wasm-bindgen = "0.2"
