[package]
name = "jexl-wasm"
version = "0.1.0"
authors = ["Nicolas Barbotte"]
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# default = ["console_error_panic_hook"]
language-service = ["jexl-3000/language-service"]

[dependencies]
jexl-3000 = { path = "../jexl-3000" }
wasm-bindgen = "0.2.84"
js-sys = "0.3"
# web-sys = { version = "0.3", features = ["console"] }

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
# console_error_panic_hook = { version = "0.1.7", optional = true }

serde.workspace = true
serde_json.workspace = true
serde-wasm-bindgen = "0.6.5"

[dev-dependencies]
wasm-bindgen-test = "0.3.34"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
