/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Evaluator {
  constructor()
  evaluate(expression: string, context?: any | undefined | null): any
  evaluateMultiple(expressions: Array<string>, context?: any | undefined | null): Array<Error | any>
}
