/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class Evaluator {
  constructor()
  evaluate(expression: string, context?: any | undefined | null): any
  evaluateMultiple(expressions: Array<string>, context?: any | undefined | null): Array<Error | any>
}
